version: '3.7'

networks:
  app:
    driver: bridge

services:
  workspace:
    build:
      context: ./workspace
      args:
        - PHP_VERSION=${PHP_VERSION}
    image: ${COMPOSE_PROJECT_NAME}_workspace:latest
    volumes:
      - ${PROJECT_PATH}:/var/htdocs
    tty: true
    networks:
      - app

  php-cli:
    build:
      context: ./php-cli
      args:
        - PHP_VERSION=${PHP_VERSION}
        - XDEBUG_ENABLE=${XDEBUG_ENABLE}
        - XDEBUG_HOST=${XDEBUG_HOST}
        - XDEBUG_PORT=${XDEBUG_PORT}
        - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
    image: ${COMPOSE_PROJECT_NAME}_cli:latest
    volumes:
      - ${PROJECT_PATH}:/var/htdocs
    networks:
      - app
